### PR TITLE
Create Create_APIs

### PR DESCRIPTION
**Pull request by melissa12345**
Please let me know if you have any additional comments.  Thanks! @sdasgupta17 @ka3ineli @yeonus

### CODE REVIEW

**Comment by ka3ineli** [comment]
Hey Melissa - Can you also add what we learned about the shipping startup company API?

Thanks!

**Comment by ka3ineli** [comment]
But otherwise :+1:

**Comment by melissa12345** [comment]
Great feedback @ka3ineli ... I will add that one, as that was a great example from class as well!

**Comment by melissa12345** [comment]
@ka3ineli  I just added the update. Do I have the thumbs up?

**Comment by ka3ineli** [comment]
AMAZINNNNNNNNNNNN' :+1:

**Comment by yeonus** [comment]
Nice job @melissa12345 !   :+1: :+1: To add APIs on Walmart example, I think payment APIs can also be the main ones, such as direct payment via PayPal.

**Pull request merged**
